name: production

# Production environment for SecureAuditAI Agent
# This environment requires manual approval and has strict protection rules

protection_rules:
  - type: required_reviewers
    settings:
      required_reviewers:
        number: 2
        dismiss_stale_reviews: true
  - type: status_checks
    settings:
      strict_required_status_checks:
        contexts:
          - "Code Quality & Security"
          - "Validate Infrastructure"
          - "Deploy to Development"
          - "Deploy to Staging"
  - type: wait_timer
    settings:
      minutes: 5
  - type: branch_protection
    settings:
      required_status_checks:
        strict: true
        contexts:
          - "Deploy to Development"
          - "Deploy to Staging"

# Environment-specific variables and secrets
# These should be configured in GitHub repository settings

# AWS Configuration for Production Environment
# - AWS_ACCESS_KEY_ID_PROD: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
# - AWS_SECRET_ACCESS_KEY_PROD: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
# - AWS_REGION: us-west-2

# Bedrock Configuration
# - BEDROCK_MODEL_ID: ${{ secrets.BEDROCK_MODEL_ID }}

# Deployment Configuration
# - STACK_NAME: secureauditai-agent-prod
# - ENVIRONMENT: prod

# Frontend Configuration
# - FRONTEND_BUCKET: secureauditai-frontend-prod
# - COGNITO_DOMAIN_PREFIX: secureauditai-prod

# Monitoring Configuration
# - CLOUDWATCH_DASHBOARD: SecureAuditAI-Prod-Dashboard
# - LOG_RETENTION_DAYS: 90

# Production-specific Configuration
# - BACKUP_RETENTION_DAYS: 365
# - MONITORING_ENABLED: true
# - ALERTS_ENABLED: true

# Environment URL (will be populated by deployment)
# - API_GATEWAY_URL: https://your-api.execute-api.us-west-2.amazonaws.com/prod
# - FRONTEND_URL: http://secureauditai-frontend-prod.s3-website-us-west-2.amazonaws.com

# Environment metadata
description: "Production environment for SecureAuditAI Agent - Requires manual approval and has strict security controls"

# Deployment settings
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false

# Environment-specific reviewers (required for production)
reviewers:
  teams:
    - "secureauditai-maintainers"
  users:
    - "admin-user"

# Wait timer for deployment (5 minutes for production)
wait_timer: 300

# Environment secrets (configured in repository settings)
# Required secrets for production:
# - AWS_ACCESS_KEY_ID_PROD
# - AWS_SECRET_ACCESS_KEY_PROD
# - BEDROCK_MODEL_ID (optional, defaults to Claude 3.5 Sonnet)

# Additional production secrets:
# - SLACK_WEBHOOK_URL (for deployment notifications)
# - PAGERDUTY_INTEGRATION_KEY (for critical alerts)
# - MONITORING_WEBHOOK_URL (for monitoring alerts)

# Environment variables (auto-populated during deployment)
# These are set by the GitHub Actions workflow
# - STACK_NAME
# - API_GATEWAY_URL
# - FRONTEND_URL
# - USER_POOL_ID
# - USER_POOL_CLIENT_ID
# - DEPLOYMENT_TIMESTAMP
# - VERSION_TAG

# Production-specific environment variables
# - PRODUCTION: true
# - LOG_LEVEL: WARN
# - BACKUP_ENABLED: true
# - COMPLIANCE_MODE: strict

# Deployment notifications
# Configure webhooks for deployment status updates
# - Slack channel: #secureauditai-deployments
# - Email notifications: devops@company.com

# Security considerations for production
# - All secrets should be rotated regularly
# - Access should be limited to authorized personnel only
# - All changes should be logged and auditable
# - Regular security scans should be performed
